site_name: StaticBTESolver
site_author: Yucheng Shi

# Configuration
theme:
  name: readthedocs
  language: en

nav:
  - Home: index.md
  - 'User Guide':
    - 'Dependencies': dependencies.md
    - 'Installation': installation.md
    - 'Command Line Tool': command-line-tool.md
    - 'Examples': examples.md
    - 'Public API': public-api.md
  - About:
    - 'About': about.md
    - 'License': license.md
    - 'Release Notes': release-notes.md