site_name: StaticBTESolver
site_author: Yucheng Shi

repo_name: yuchengs/StaticBTESolver
repo_url: https://github.com/yuchengs/StaticBTESolver

# Configuration
theme:
  name: readthedocs

nav:
  - Home: index.md
  - 'User Guide':
    - 'Dependencies': dependencies.md
    - 'Installation': installation.md
    - 'Command Line Tool': command-line-tool.md
    - 'Examples': examples.md
    - 'Public API': html/index.html
  - About:
    - 'About': about.md
    - 'License': license.md
    - 'Release Notes': release-notes.md